services:
  server:
    build: ./apps/web/server
    container_name: focusflow-server
    ports:
      - "3001:3001"
    env_file:
      - ./apps/web/server/.env
    volumes:
      - ./apps/web/server:/app
      - /app/node_modules

  client:
    build: ./apps/web/client
    container_name: focusflow-client
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/client/.env
    depends_on:
      - server
    volumes:
      - ./apps/web/client:/app
      - /app/node_modules